version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-ejem3-db2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ozktphv6tiak"
s3_prefix = "serverless-ejem3-db"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
