AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless_ejem3_db

  Sample SAM Template for serverless_ejem3_db

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 128

Resources:
  DbAppFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: DbApp
      Handler: es.codeurjc.serverless.db.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        lambdaGetAllUsers:
          Type: Api
          Properties:
            Path: /users/
            Method: GET
        lambdaAddUser:
          Type: Api
          Properties:
            Path: /users/
            Method: POST
        lambdaUpdateUser:
          Type: Api
          Properties:
            Path: /users/{userid}
            Method: PUT
        lambdaDeleteUser:
          Type: Api
          Properties:
            Path: /users/{userid}
            Method: DELETE
      Policies:
        # Policies to allow the execution of the indicated actions to the table described in Resource
        - DynamoDBCrudPolicy:
            TableName:
              !Ref UsersTable
  UsersTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: appusers
      AttributeDefinitions:
        - AttributeName: userid
          AttributeType: S
      KeySchema:
        - AttributeName: userid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PublicApi:
    Description: "API Gateway endpoint URL for ManageFiles App"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
