AWSTemplateFormatVersion: 2010-09-09
Description: EC2

Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: codenaeva-aws-elastest
      ImageId: ami-035966e8adab4aaad
      InstanceType: "t2.micro"
      SecurityGroupIds:
        - sg-0ddd30794dedc1ba3
      UserData: !Base64 |
        #!/bin/bash -ex
        apt-get update && apt-get install -y nginx
      Tags:
        - Key: Name
          Value: cf-sample-1

Outputs:
  WebSiteURL:
    Value:
      !Join
        - ''
        - - "http://"
          - !GetAtt myEC2Instance.PublicDnsName
    Description: "Nginx website"