AWSTemplateFormatVersion: 2010-09-09
Description: EC2

Parameters: 
  KeyName:
    Description: Key pair to use in EC2 instance
    Type: AWS::EC2::KeyPair::KeyName

Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      ImageId:  ami-08ca3fed11864d6bb
      InstanceType: "t2.micro"
      SecurityGroupIds:
        - sg-05ffda682903ac61b
      UserData: !Base64 |
        #!/bin/bash -ex
        apt update && apt install -y nginx
      Tags:
        - Key: Name
          Value: cf-sample-1

Outputs:
  WebSiteURL:
    Value:
      !Join
        - ''
        - - "http://"
          - !GetAtt myEC2Instance.PublicDnsName
    Description: "Nginx website"