AWSTemplateFormatVersion: 2010-09-09
Description: EC2

Parameters: 
  KeyName:
    Description: Key pair to use in EC2 instance
    Type: AWS::EC2::KeyPair::KeyName

Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      ImageId: ami-08ca3fed11864d6bb
      InstanceType: "t2.micro"
      Monitoring: true
      SecurityGroups:
        - !Ref mySecurityGroup
      UserData: !Base64 |
        #!/bin/bash -ex
        apt-get update && apt-get install -y openjdk-8-jre-headless
        wget https://github.com/MasterCloudApps/2.2.Patrones-y-arquitecturas-de-servicios-web/releases/download/0.1.0/blog-cqrs-ejem1-1.0.0.jar
        java -jar blog-cqrs-ejem1-1.0.0.jar
      Tags:
        - Key: Name
          Value: cf-sample-4
  mySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: spring-8080-8443
      GroupDescription: "SG for Nginx with egress ports 80 & 443"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8443'
          ToPort: '8443'
          CidrIp: 0.0.0.0/0

Outputs:
  WebSiteURL:
    Value:
      !Join
        - ''
        - - "http://"
          - !GetAtt myEC2Instance.PublicDnsName
          - ":8080"
          - "/api/post/"
    Description: "Ejemplo 1 CQRS - Blog"