dist: trusty
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get update
  - sudo apt-get install -y openjdk-8-jdk
  
language: java

script:
  - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
  - mvn package docker:build -DpushImage
